name: cd
run-name: Workflow ${{ github.workflow }} triggered by @${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build-jar:
    name: build-jar
    runs-on: ubuntu-22.04
    steps:
      - name: Pull git repository
        uses: actions/checkout@v4.1.5
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21.0.3
          distribution: liberica
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
      - name: Build package
        run: ./gradlew clean build --exclude-task test --exclude-task jar
        env:
          INTERNAL_REPOSITORY: ${{ vars.INTERNAL_REPOSITORY }}
          GITHUB_ACTOR: ${{ github.actor }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - name: Upload jar
        uses: actions/upload-artifact@v4.3.3
        with:
          name: jar
          path: build/libs/*.jar
  build-image:
    name: build-image
    runs-on: ubuntu-22.04
    needs: build-jar
    steps:
      - name: Pull git repository
        uses: actions/checkout@v4.1.5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Download jar
        uses: actions/download-artifact@v4.1.7
        with:
          name: jar
          path: build/libs
      - name: Build and push docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ghcr.io/raymundoz/librarium-auth:latest
  deploy:
    name: deploy
    runs-on: ubuntu-22.04
    needs: build-image
    environment: production
    steps:
      - name: Set ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Update service on prod
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} './update-librarium.sh ${{ github.actor }} ${{ secrets.PACKAGES_TOKEN }} ${{ vars.SERVICE_NAME }}'
